import { describe, expect, it } from 'vitest';
import {
  CandidateConversionDeclarationSchema,
  CandidateConversionPairClaimsSchema,
  CandidateConversionCheckSchema,
  GetCandidateConversionProvenanceOutputSchema,
} from '../src/ingestion/candidate-conversion.ts';

describe('versioned source manifest pair claims', () => {
  const pair = {
    original: {
      assetId: 'a1000000-0000-4000-8000-000000000001',
      sha256: 'a'.repeat(64),
      byteSize: 12,
    },
    prepared: {
      assetId: 'a1000000-0000-4000-8000-000000000002',
      sha256: 'b'.repeat(64),
      byteSize: 18,
    },
    sourceLocalWorkId: 'monthly-2023-04',
    historicalToolVersion: null,
  };
  const claims = {
    schemaVersion: 'wiser.candidate-conversion-claims.v1',
    pairs: [pair],
  };
  it('accepts only partial claims, leaving actual M identity to the server', () => {
    expect(CandidateConversionPairClaimsSchema.parse(claims)).toEqual(claims);
  });
  it.each(['manifest', 'verified', 'toolDigest'])(
    'rejects caller %s authority fields',
    (field) => {
      expect(
        CandidateConversionPairClaimsSchema.safeParse({
          ...claims,
          pairs: [
            { ...pair, [field]: field === 'verified' ? true : 'untrusted' },
          ],
        }).success,
      ).toBe(false);
    },
  );
  it('rejects unsupported versions, empty/oversized lists and duplicate case-folded P', () => {
    for (const value of [
      { ...claims, schemaVersion: 'wiser.candidate-conversion-claims.v2' },
      { ...claims, pairs: [] },
      {
        ...claims,
        pairs: Array.from({ length: 129 }, (_, index) => ({
          ...pair,
          prepared: {
            ...pair.prepared,
            assetId: `a2000000-0000-4000-8000-${String(index).padStart(12, '0')}`,
          },
        })),
      },
      {
        ...claims,
        pairs: [
          pair,
          {
            ...pair,
            prepared: {
              ...pair.prepared,
              assetId: pair.prepared.assetId.toUpperCase(),
            },
          },
        ],
      },
      {
        ...claims,
        pairs: [
          {
            ...pair,
            prepared: {
              ...pair.prepared,
              assetId: pair.original.assetId.toUpperCase(),
            },
          },
        ],
      },
    ])
      expect(CandidateConversionPairClaimsSchema.safeParse(value).success).toBe(
        false,
      );
  });
});

const id = (suffix: number) =>
  `10000000-0000-4000-8000-${String(suffix).padStart(12, '0')}`;
const reference = {
  kind: 'ingestion-candidate',
  ingestionId: id(1),
  processingBatchId: id(2),
  reviewHash: 'a'.repeat(64),
};
const declaration = {
  schemaVersion: 'wiser.candidate-conversion-pair.v1',
  original: { assetId: id(3), sha256: 'b'.repeat(64), byteSize: 12 },
  prepared: { assetId: id(4), sha256: 'c'.repeat(64), byteSize: 18 },
  manifest: { assetId: id(5), sha256: 'd'.repeat(64) },
  sourceLocalWorkId: 'monthly-local-2023-04',
  historicalToolVersion: null,
};
const check = {
  schemaVersion: 1,
  resultId: id(6),
  reference,
  ...Object.fromEntries(
    Object.entries(declaration).filter(([key]) => key !== 'schemaVersion'),
  ),
  kind: 'HISTORICAL_EQUIVALENCE',
  state: 'VERIFIED_EQUIVALENT',
  rule: { id: 'candidate-word-equivalence', version: '1.0.0' },
  tool: {
    name: 'trusted-converter',
    version: 'synthetic-test',
    digest: 'e'.repeat(64),
  },
  reconvertedSha256: 'f'.repeat(64),
  comparisonDigest: '1'.repeat(64),
  comparison: {
    tableCount: 1,
    physicalCellCount: 2,
    emptyCellCount: 1,
    paragraphCount: 3,
    monthTitleCount: 1,
    differenceCount: 0,
    differences: [],
  },
  failureReason: null,
};

describe('candidate conversion trust boundary', () => {
  it('keeps distinct original/prepared bytes and unknown historical tool as a declaration', () => {
    expect(CandidateConversionDeclarationSchema.parse(declaration)).toEqual(
      declaration,
    );
  });
  it('does not accept a caller verification flag or duplicate/missing members', () => {
    expect(
      CandidateConversionDeclarationSchema.safeParse({
        ...declaration,
        verified: true,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionDeclarationSchema.safeParse({
        ...declaration,
        prepared: declaration.original,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionDeclarationSchema.safeParse({
        ...declaration,
        manifest: { ...declaration.manifest, assetId: id(3) },
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionDeclarationSchema.safeParse({
        ...declaration,
        original: undefined,
      }).success,
    ).toBe(false);
  });
  it('represents a server check without claiming that historical P was generated by the platform', () => {
    expect(CandidateConversionCheckSchema.parse(check)).toEqual(check);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        platformGenerated: true,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({ ...check, tool: null })
        .success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        comparisonDigest: null,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        comparison: { ...check.comparison, differenceCount: 1 },
      }).success,
    ).toBe(false);
  });
  it('permits an honest unconfigured result but not a consumable or unbounded one', () => {
    const unavailable = {
      ...check,
      state: 'UNVERIFIABLE',
      tool: null,
      reconvertedSha256: null,
      comparisonDigest: null,
      comparison: null,
      failureReason: 'TOOL_UNAVAILABLE',
    };
    expect(CandidateConversionCheckSchema.parse(unavailable)).toEqual(
      unavailable,
    );
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...unavailable,
        failureReason: null,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        comparison: {
          ...check.comparison,
          differences: Array(17).fill('table:1/cell:1'),
          differenceCount: 17,
        },
      }).success,
    ).toBe(false);
  });
  it('returns a null check only for a fixed readable prepared member and rejects foreign check identity', () => {
    const response = { reference, preparedAssetId: id(4), check: null };
    expect(
      GetCandidateConversionProvenanceOutputSchema.parse(response),
    ).toEqual(response);
    expect(
      GetCandidateConversionProvenanceOutputSchema.parse({
        ...response,
        check,
      }),
    ).toEqual({ ...response, check });
    expect(
      GetCandidateConversionProvenanceOutputSchema.safeParse({
        ...response,
        preparedAssetId: id(3),
        check,
      }).success,
    ).toBe(false);
    expect(
      GetCandidateConversionProvenanceOutputSchema.safeParse({
        ...response,
        reference: { ...reference, reviewHash: '2'.repeat(64) },
        check,
      }).success,
    ).toBe(false);
  });
});
