import { describe, expect, it } from 'vitest';
import {
  CandidateConversionDeclarationSchema,
  CandidateConversionCheckSchema,
  GetCandidateConversionProvenanceOutputSchema,
} from '../src/ingestion/candidate-conversion.ts';

const id = (suffix: number) =>
  `10000000-0000-4000-8000-${String(suffix).padStart(12, '0')}`;
const reference = {
  kind: 'ingestion-candidate',
  ingestionId: id(1),
  processingBatchId: id(2),
  reviewHash: 'a'.repeat(64),
};
const declaration = {
  schemaVersion: 'wiser.candidate-conversion-pair.v1',
  original: { assetId: id(3), sha256: 'b'.repeat(64), byteSize: 12 },
  prepared: { assetId: id(4), sha256: 'c'.repeat(64), byteSize: 18 },
  manifest: { assetId: id(5), sha256: 'd'.repeat(64) },
  sourceLocalWorkId: 'monthly-local-2023-04',
  historicalToolVersion: null,
};
const check = {
  schemaVersion: 1,
  resultId: id(6),
  reference,
  ...Object.fromEntries(
    Object.entries(declaration).filter(([key]) => key !== 'schemaVersion'),
  ),
  kind: 'HISTORICAL_EQUIVALENCE',
  state: 'VERIFIED_EQUIVALENT',
  rule: { id: 'candidate-word-equivalence', version: '1.0.0' },
  tool: {
    name: 'trusted-converter',
    version: 'synthetic-test',
    digest: 'e'.repeat(64),
  },
  reconvertedSha256: 'f'.repeat(64),
  comparisonDigest: '1'.repeat(64),
  comparison: {
    tableCount: 1,
    physicalCellCount: 2,
    emptyCellCount: 1,
    paragraphCount: 3,
    monthTitleCount: 1,
    differenceCount: 0,
    differences: [],
  },
  failureReason: null,
};

describe('candidate conversion trust boundary', () => {
  it('keeps distinct original/prepared bytes and unknown historical tool as a declaration', () => {
    expect(CandidateConversionDeclarationSchema.parse(declaration)).toEqual(
      declaration,
    );
  });
  it('does not accept a caller verification flag or swapped/missing members', () => {
    expect(
      CandidateConversionDeclarationSchema.safeParse({
        ...declaration,
        verified: true,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionDeclarationSchema.safeParse({
        ...declaration,
        prepared: declaration.original,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionDeclarationSchema.safeParse({
        ...declaration,
        manifest: { ...declaration.manifest, assetId: id(3) },
      }).success,
    ).toBe(false);
  });
  it('represents a server check without claiming that historical P was generated by the platform', () => {
    expect(CandidateConversionCheckSchema.parse(check)).toEqual(check);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        platformGenerated: true,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({ ...check, tool: null })
        .success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        comparisonDigest: null,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        comparison: { ...check.comparison, differenceCount: 1 },
      }).success,
    ).toBe(false);
  });
  it('permits an honest unconfigured result but not a consumable or unbounded one', () => {
    const unavailable = {
      ...check,
      state: 'UNVERIFIABLE',
      tool: null,
      reconvertedSha256: null,
      comparisonDigest: null,
      comparison: null,
      failureReason: 'TOOL_UNAVAILABLE',
    };
    expect(CandidateConversionCheckSchema.parse(unavailable)).toEqual(
      unavailable,
    );
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...unavailable,
        failureReason: null,
      }).success,
    ).toBe(false);
    expect(
      CandidateConversionCheckSchema.safeParse({
        ...check,
        comparison: {
          ...check.comparison,
          differences: Array(17).fill('table:1/cell:1'),
          differenceCount: 17,
        },
      }).success,
    ).toBe(false);
  });
  it('returns a null check only for a fixed readable prepared member and rejects foreign check identity', () => {
    const response = { reference, preparedAssetId: id(4), check: null };
    expect(
      GetCandidateConversionProvenanceOutputSchema.parse(response),
    ).toEqual(response);
    expect(
      GetCandidateConversionProvenanceOutputSchema.parse({
        ...response,
        check,
      }),
    ).toEqual({ ...response, check });
    expect(
      GetCandidateConversionProvenanceOutputSchema.safeParse({
        ...response,
        preparedAssetId: id(3),
        check,
      }).success,
    ).toBe(false);
    expect(
      GetCandidateConversionProvenanceOutputSchema.safeParse({
        ...response,
        reference: { ...reference, reviewHash: '2'.repeat(64) },
        check,
      }).success,
    ).toBe(false);
  });
});
